### ISSUE TITLE
Feature request: Create Url from current page url (from $_SERVER)

### ISSUE THREAD

**Issue by Nayjest** [Riimu/Kit-UrlParser#2]

**Comment by Riimu** [comment]
Apologies for the late answer. However, I feel this is somewhat out of the scope of this library. The problem with this particular feature is that specifics of how to extract the current page URL (or request URI) from the `$_SERVER` superglobal is highly architecture dependent.

Creating a request URI from the most common case is not particularly hard and could be achieved using something like:

```php
<?php

require 'vendor/autoload.php';

$parser = new \Riimu\Kit\UrlParser\UriParser();
$uri = $parser->parse(sprintf(
    '%s://%s%s',
    empty($_SERVER['HTTPS']) || $_SERVER['HTTPS'] === 'off' ? 'http' : 'https',
    $_SERVER['HTTP_HOST'],
    $_SERVER['REQUEST_URI']
));

echo $uri;
```

However, this only covers the most common scenario. I don't feel like implementing something that incomplete is worth it. On the other hand, I don't really have the expertise nor the platforms to test and develop a more complete solution that works across many different platforms.
